package com.samoondigital.yojnaplus.domain.model

data class IndiaState(val code: String, val name: String)

val INDIA_STATES: List<IndiaState> = listOf(
    IndiaState("S01", "Andhra Pradesh"),
    IndiaState("S02", "Arunachal Pradesh"),
    IndiaState("S03", "Assam"),
    IndiaState("S04", "Bihar"),
    IndiaState("S05", "Goa"),
    IndiaState("S06", "Gujarat"),
    IndiaState("S07", "Haryana"),
    IndiaState("S08", "Himachal Pradesh"),
    IndiaState("S10", "Karnataka"),
    IndiaState("S11", "Kerala"),
    IndiaState("S12", "Madhya Pradesh"),
    IndiaState("S13", "Maharashtra"),
    IndiaState("S14", "Manipur"),
    IndiaState("S15", "Meghalaya"),
    IndiaState("S16", "Mizoram"),
    IndiaState("S17", "Nagaland"),
    IndiaState("S18", "Odisha"),
    IndiaState("S19", "Punjab"),
    IndiaState("S20", "Rajasthan"),
    IndiaState("S21", "Sikkim"),
    IndiaState("S22", "Tamil Nadu"),
    IndiaState("S23", "Tripura"),
    IndiaState("S24", "Uttar Pradesh"),
    IndiaState("S25", "West Bengal"),
    IndiaState("S26", "Chhattisgarh"),
    IndiaState("S27", "Jharkhand"),
    IndiaState("S28", "Uttarakhand"),
    IndiaState("S29", "Telangana"),
    IndiaState("U01", "Andaman & Nicobar Islands"),
    IndiaState("U02", "Chandigarh"),
    IndiaState("U03", "Dadra & Nagar Haveli and Daman & Diu"),
    IndiaState("U05", "NCT of Delhi"),
    IndiaState("U06", "Lakshadweep"),
    IndiaState("U07", "Puducherry"),
    IndiaState("U08", "Jammu and Kashmir"),
    IndiaState("U09", "Ladakh"),
)
